name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout репозиторію
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Встановлення Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "^3.12"  # Заміни на версію Python, яку використовує проект

    # 3. Встановлення Poetry
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/backend/.local/bin" >> $GITHUB_PATH

    # 4. Запуск середовища
    - name: Run space
      run: |
        cd backend
        poetry shell  # Заміни на команду для запуску тестів
        
    # 5. Встановлення залежностей
    - name: Install dependencies
      run: |
        cd backend
        poetry install

      
     # 6. Запуск серверу
    - name: Run server
      run: |
        cd backend
        PYTHONPATH=$(pwd) uvicorn backend.main:app --reload
      
    # 5. Запуск тестів
    # - name: Run tests
    #  run: poetry run pytest  # Заміни на команду для запуску тестів
      
    
